const express=require("express");
const app=express(); app.use(express.json());
const PORT=process.env.PORT||10000;
const cfg={provider:(process.env.MARKET_DATA_PROVIDER||"demo").toLowerCase(),key:process.env.MARKET_DATA_API_KEY||"",symbol:process.env.MARKET_DATA_SYMBOL||"XAU/USD"};
let bot={running:false,mode:"paper",tradesToday:0,trades:[],lastSignal:"WAIT",lastPrice:null};

function ema(v,p){if(v.length<p)return null;let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p,k=2/(p+1);for(let i=p;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,p){if(v.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){let d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){let d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al===0?100:100-100/(1+ag/al)}
function demo(n=120){let a=[],p=2650,t=Date.now();for(let i=n-1;i>=0;i--){p+=(Math.random()-.5)*1.8+Math.sin(i/8)*.15;a.push({datetime:new Date(t-i*300000).toISOString(),open:p-.3,high:p+1,low:p-1,close:p})}return a}
async function candles(){if(cfg.provider!=="twelvedata"||!cfg.key)return {candles:demo(),source:"demo"};let u=new URL("https://api.twelvedata.com/time_series");u.searchParams.set("symbol",cfg.symbol);u.searchParams.set("interval","5min");u.searchParams.set("outputsize","120");u.searchParams.set("apikey",cfg.key);let r=await fetch(u),d=await r.json();if(!r.ok||!d.values)throw Error(d.message||"Market data error");return {candles:d.values.reverse().map(x=>({datetime:x.datetime,open:+x.open,high:+x.high,low:+x.low,close:+x.close})),source:"twelvedata"}}
function analyze(c){let v=c.map(x=>x.close),f=ema(v,9),s=ema(v,21),rr=rsi(v,14),pv=v.slice(0,-1),pf=ema(pv,9),ps=ema(pv,21),sig="WAIT";if(pf!=null&&ps!=null&&pf<=ps&&f>s&&rr>50)sig="BUY";if(pf!=null&&ps!=null&&pf>=ps&&f<s&&rr<50)sig="SELL";return {signal:sig,ema9:f,ema21:s,rsi:rr}}
app.get("/api/health",(q,s)=>s.json({ok:true,mode:"paper",liveTrading:false,provider:cfg.provider,symbol:cfg.symbol,interval:"5min"}));
app.get("/api/status",(q,s)=>s.json(bot));
app.get("/api/market",async(q,s)=>{try{let x=await candles(),a=analyze(x.candles);bot.lastPrice=x.candles.at(-1).close;bot.lastSignal=a.signal;s.json({...x,analysis:a})}catch(e){s.status(502).json({error:e.message})}});
app.post("/api/bot/start",(q,s)=>{bot.running=true;s.json(bot)});
app.post("/api/bot/stop",(q,s)=>{bot.running=false;s.json(bot)});
app.post("/api/paper/trade",async(q,s)=>{try{if(!bot.running)return s.status(400).json({error:"Start the bot first"});let x=await candles(),a=analyze(x.candles),p=x.candles.at(-1).close;if(a.signal==="WAIT")return s.json({executed:false,reason:"No signal",analysis:a,price:p});let tr={id:Date.now(),side:a.signal,price:p,time:new Date().toISOString()};bot.trades.unshift(tr);bot.tradesToday++;s.json({executed:true,trade:tr})}catch(e){s.status(502).json({error:e.message})}});
app.get("/",(q,s)=>s.type("html").send(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>XAUUSD M5 iPad Bot</title><style>body{font-family:-apple-system,Arial;background:#f5f5f7;margin:0}.w{max-width:700px;margin:auto;padding:18px}.c{background:white;border-radius:18px;padding:18px;margin:12px 0;box-shadow:0 2px 10px #0001}.g{display:grid;grid-template-columns:1fr 1fr;gap:10px}.s{background:#f2f2f7;border-radius:14px;padding:14px}button{padding:14px;border:0;border-radius:12px;margin:4px;font-size:16px}.dark{background:#111;color:#fff}</style><div class=w><div class=c><h1>🥇 XAUUSD M5 Bot</h1><p>iPad Edition • EMA 9/21 + RSI 14 • PAPER ONLY</p></div><div class=c><h2 id=sg>WAIT</h2><div id=src>Loading...</div></div><div class=g><div class=s>Price<br><b id=p>—</b></div><div class=s>RSI<br><b id=r>—</b></div><div class=s>EMA 9<br><b id=e9>—</b></div><div class=s>EMA 21<br><b id=e21>—</b></div></div><div class=c><button class=dark onclick="go('/api/bot/start')">Start</button><button onclick="go('/api/bot/stop')">Stop</button><button onclick="go('/api/paper/trade')">Paper Trade Signal</button><p id=st>Stopped</p></div><div class=c>BUY = EMA 9 crosses above EMA 21 + RSI &gt; 50.<br>SELL = EMA 9 crosses below EMA 21 + RSI &lt; 50.<br><br>No real broker orders are sent.</div></div><script>async function j(u,o){return(await fetch(u,o)).json()}async function go(u){let x=await j(u,{method:'POST'});st.textContent=x.error||('Bot '+(x.running?'running':'stopped'));load()}async function load(){let m=await j('/api/market'),b=await j('/api/status');if(m.analysis){sg.textContent=m.analysis.signal;src.textContent='Source: '+m.source;p.textContent=m.candles.at(-1).close.toFixed(2);r.textContent=m.analysis.rsi?.toFixed(2)||'—';e9.textContent=m.analysis.ema9?.toFixed(2)||'—';e21.textContent=m.analysis.ema21?.toFixed(2)||'—'}st.textContent=(b.running?'Running':'Stopped')+' • Trades today: '+b.tradesToday}load();setInterval(load,30000)</script>`));
app.listen(PORT,"0.0.0.0",()=>console.log("XAUUSD iPad bot ready"));
